### ISSUE TITLE
How can I add a access key

### ISSUE THREAD

**Issue by pengyiwang** [mjoslyn/react-prismic-hocs#1]
We're not using an open repository, how can I add our access key?

**Comment by mjoslyn** [comment]
Hi there. This was an extraction of components for a project that didn't need an api key, so the functionality isn't there right now. I'll take a look, but PR's welcome! I'd start by adding apiOptions in https://github.com/mjoslyn/react-prismic-hocs/blob/master/modules/queries.js and add the props to each of the components.

**Comment by mjoslyn** [comment]
I've added an apiOptions key, do you mind trying updating your package it out? Please note the predicate options are now ```predicateOptions``` instead of ```options``` 
Thanks!

**Comment by pengyiwang** [comment]
Thank you! it works, awesome
