### ISSUE TITLE
No update when query changes

### ISSUE THREAD

**Issue by misto** [mjoslyn/react-prismic-hocs#2]
First of all, thanks for writing this library! It's very useful. But I've come across a small problem when using it. I have a query that depends on a router parameter:

```
<Query ...
  query={[
    [Predicates.at("my.blog_post.uid", match.params.uid)],
    {
      fetchLinks: ["author.name", "category.name"]
    }
  ]}
>
```

Now when the uid in the route changes - the component is still mounted - it does not fetch the new document. I think this should be done with a query in componentDidUpdate.

**Comment by mjoslyn** [comment]
Sorry for the late response @misto!

I've run into a similar issue on my side that I resolved forcing a re-render by including a key in the query props, which will force a rerender and trigger a new query.

```
<Query ...
  key={match.params.uid}
query={[
    [Predicates.at("my.blog_post.uid", match.params.uid)],
    {
      fetchLinks: ["author.name", "category.name"]
    }
  ]}
>

**Comment by mjoslyn** [comment]
Added note about refetching & routing in docs
