### ISSUE TITLE
No data with prismic.io

### ISSUE THREAD

**Issue by snrn-Pontus** [mjoslyn/react-prismic-hocs#3]
I had a problem with getting a empty data field when using this. 

I edited it to use prismic-javascript instead of prismic io and was able to get data properly from the requests.

Would it be possible for you to fix this? I could fork it and change it, but I would need to upload it to npm to use it after the changes and I would rather not take any credit for it when I am just changing a dependancy.

**Comment by mjoslyn** [comment]
Hey @snrn-Pontus  - sorry for the delay. Which api version are you using?
